Nop.Plugin.Uga.Partners/Models/PartnersModel.cs
using System;
using Nop.Web.Framework.Mvc;

namespace Nop.Plugin.Uga.Partners.Models
{
    
    public partial class PartnersModel : BaseNopEntityModel
    {
        public PartnersModel()
        {
           
        }

        public string Name { get; set; }
        public string Description { get; set; }
        public string City { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
		public string Latitude { get; set; }
		public string Longtitude { get; set; }
		public string Title { get; set; }
		public string Email { get; set; }
	}
}

Nop.Plugin.Uga.Partners/Controllers/PartnersController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using Nop.Core;
using Nop.Core.Caching;
using Nop.Core.Domain.Catalog;
using Nop.Plugin.Uga.Partners.Infrastructure.Cache;
using Nop.Plugin.Uga.Partners.Models;
using Nop.Services.Catalog;
using Nop.Services.Customers;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Media;
using Nop.Services.Security;
using Nop.Services.Seo;
using Nop.Services.Stores;
using Nop.Services.Tax;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Security;
using Nop.Web.Framework.Kendoui;
using Nop.Web.Framework.Mvc;
using Nop.Core.Domain.Customers;
using Nop.Services.Common;
using Nop.Core.Data;
using Nop.Core.Domain.Common;
using System.Collections;
using Nop.Plugin.Uga.Partners.Services;
using Nop.Plugin.Uga.Partners.Domain;

namespace Nop.Plugin.Uga.Partners.Controllers
{
    [NopHttpsRequirement(SslRequirement.NoMatter)]
    public class PartnersController : BasePluginController
    {
        #region Fields

      
        private readonly IWorkContext _workContext;
        private readonly IPartnerService _pService;
        private readonly IRepository<PartnersRecord> _pRepository;
        

        #endregion

        #region Ctor

        public PartnersController(IPartnerService pService,
            IWorkContext workContext,
            IRepository<PartnersRecord> pRepository
           
            )
        {
            this._pService = pService;
            this._workContext = workContext;
            this._pRepository = pRepository;
            
        }
        
        #endregion
        
        #region Utilities

        #endregion

        #region Methods

 
        public ActionResult Index()
        {
            return View("~/Plugins/Uga.Partners/Views/Partners/Index.cshtml");
        }


        [HttpPost]
        public ActionResult PartnersGridList(DataSourceRequest request, string id) {
            IList<PartnersModel> partners;
            if (!string.IsNullOrEmpty(id)) {
                 partners = (from c in _pRepository.Table.AsEnumerable()
                                                 where (c.City.ToUpper().Contains(id.ToUpper()) || c.PostCode.ToUpper().Contains(id.ToUpper()))
                                                 select new PartnersModel {
                                                     Id = c.Id, Name = c.Name, Title = c.Description, Email = c.Email,
                                                     Telephone = c.Telephone, PostCode = c.PostCode,
                                                     Address = c.Address, City = c.City
                                                 }).Distinct().ToList();
            }
            else {
                 partners = (from c in _pRepository.Table.AsEnumerable()
                                                 select new PartnersModel {
                                                     Id = c.Id, Name = c.Name, Title = c.Description, Email = c.Email,
                                                     Telephone = c.Telephone, PostCode = c.PostCode,
                                                     Address = c.Address, City = c.City
                                                 }).Distinct().ToList();
            }

            var gridModel = new DataSourceResult {
                Data = partners,
                Total = partners.Count()
            };

            return Json(gridModel, JsonRequestBehavior.AllowGet);
        }

        
        public ActionResult PartnersList(string id)
        {
            IList<PartnersModel> partners;
            if (!string.IsNullOrEmpty(id)) {
                partners = (from c in _pRepository.Table.AsEnumerable()
                            where (c.City.ToUpper().Contains(id.ToUpper()) || c.PostCode.ToUpper().Contains(id.ToUpper()))
                            select new PartnersModel {
                                Id = c.Id, Name = c.Name, Title = c.Description, Email = c.Email, Description = c.Description,
                                Telephone = c.Telephone, PostCode = c.PostCode,
                                Address = c.Address, City = c.City, Latitude = c.Latitude, Longtitude = c.Longtitude
                            }).Distinct().ToList();

            }
            else {
                partners = (from c in _pRepository.Table.AsEnumerable()
                            select new PartnersModel {
                                Id = c.Id, Name = c.Name, Title = c.Description, Email = c.Email, Description = c.Description,
                                Telephone = c.Telephone, PostCode = c.PostCode,
                                Address = c.Address, City = c.City, Latitude = c.Latitude, Longtitude = c.Longtitude
                            }).Distinct().ToList();
            }
           

            return Json(partners, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}   

Nop.Plugin.Uga.Partners/Views/Partners/Index.cshtml
@model PartnersModel
@using System.Globalization;
@using Nop.Plugin.Uga.Partners.Models;

@{
    Layout = "~/Views/Shared/_ColumnsOne.cshtml";
}






<script type="text/javascript">
    var gmarkers = [];
    var map;




    $(document).ready(function () {

        $('#showGrid').click(function (e) {

            $("#customers-grid").data("kendoGrid").dataSource.read();
            $("#customers-grid").css("display", "block");

            var mapProp = {
                center: new google.maps.LatLng(40.67418, 22.80549), //Greece Lat Long
                zoom: 6,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            for (i = 0; i < gmarkers.length; i++) {
                gmarkers[i].setMap(null);
            }

            var purl = '@Url.Action("PartnersList", "Partners", new { id = "__param__" })';
            purl = purl.replace('__param__', $("#searchTerm").val());

            $.ajax({
                type: "GET",
                url: purl, //"../Map/Search"
                contentType: "application/json; charset=utf-8",
                data: additionalInfo,
                dataType: "json",
                success: function (data) {
                    var table = "<table class='table'>";
                    $.each(data, function (index, value) {
                        table += "<tr><td>" + value.Name + "</td></tr>";
                        var latlng = new google.maps.LatLng(value.Latitude, value.Longtitude);
                        var marker = new google.maps.Marker({
                            position: latlng,
                            map: map,
                            icon: 'http://www.navaideas.gr/Themes/UgaShop/Content/Images/nava/marker.png',
                            title: value.Description + '\n' + value.Name + '\n ' + value.Address + ' TK: ' + value.PostCode + '\n' + value.Telephone + '\n' + value.Email
                        });

                        gmarkers.push(marker);

                    });
                    table += "</table>";
                    $("#myData").html(table);


                }
            });
            map = new google.maps.Map(document.getElementById("googleMap"), mapProp);

        });

        onPageLoad();
    });

    function onPageLoad() {


        function initialize() {

            $("#customers-grid").data("kendoGrid").dataSource.read();
            $("#customers-grid").css("display", "block");

            var mapProp = {
                center: new google.maps.LatLng(40.67418, 22.80549), //Greece Lat Long
                zoom: 6,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            for (i = 0; i < gmarkers.length; i++) {
                gmarkers[i].setMap(null);
            }


            $.ajax({
                type: "POST",
                url: '@Url.Action("PartnersList", "Partners")', //"../Map/Search"
                contentType: "application/json; charset=utf-8",

                dataType: "json",
                success: function (data) {
                    var table = "<table class='table'>";
                    $.each(data, function (index, value) {
                        table += "<tr><td>" + value.Name + "</td></tr>";
                        var latlng = new google.maps.LatLng(value.Latitude, value.Longtitude);
                        var marker = new google.maps.Marker({
                            position: latlng,
                            map: map,
                            icon: 'http://www.navaideas.gr/Themes/UgaShop/Content/Images/nava/marker.png',
                            title: value.Description + '\n' + value.Name + '\n ' + value.Address + ' TK: ' + value.PostCode + '\n' + value.Telephone + '\n' + value.Email
                        });

                        gmarkers.push(marker);

                    });
                    table += "</table>";
                    $("#myData").html(table);


                }
            });
            map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
        }

        google.maps.event.addDomListener(window, 'load', initialize);

    }

</script>



<script>

   

    function additionalInfo() {
        var info = $("#searchTerm").val();
        if (info) {
            return {
                id: info
            };
        }
    }
</script>

<style>
    
    #googleMap {
        height: 550px;
        width: 100%;
    }
</style>


<div class="page home-page">
    <div class="page-body">
        <span id="lbSearch">@T("Uga.Partners.Search").Text</span> 
        <input type="text" id="searchTerm" name="text" value="" /><br />
        <input id='showGrid' type="button" value="@T("Search.Searchbox.Tooltip")" />

        <h2>@T("Uga.Partners.Shops")</h2>
        <br />
        <div class="row">
           
            <div class="col-md-6">
                <table class="adminContent">
                    <tr>
                        <td>
                            <div id="customers-grid"></div>

                            <script>
                    $(document).ready(function () {
                        $("#customers-grid").kendoGrid({
                            autoBind: false,
                            dataSource: {
                                //group: { field: "City" },
                                type: "json",
                                transport: {
                                    read: {
                                        url: "@Html.Raw(Url.Action("PartnersGridList", "Partners"))",
                                        type: "POST",
                                        dataType: "json",
                                        data: additionalInfo
                                    }
                                },
                                schema: {
                                    data: "Data",
                                    total: "Total",
                                    errors: "Errors"
                                },
                                error: function(e) {
                                    display_kendoui_grid_error(e);
                                    this.cancelChanges();
                                },
                                pageSize: 20,
                                serverPaging: true,
                                serverFiltering: true,
                                serverSorting: true
                            },
                            height: 550,
                            sortable: {
                                mode: "single",
                                allowUnsort: false
                            },
                            pageable: false,
                            scrollable: true,
                            selectable:true,
                            columns: [

                                {
                                    field: "Title",
                                    title: "@T("Admin.Customers.Customers.Fields.FullName")",
                                    width: 150
                                },


                               {
                                   field: "Telephone",
                                    title: "@T("Admin.Customers.Customers.Fields.Phone")",
                                    width: 90
                                },


                               {
                                   field: "City",
                                   title: "@T("Admin.Customers.Customers.Fields.City")",
                                width: 80
                               },

                                {
                                    field: "Address",
                                    title: "@T("Admin.Customers.Customers.Fields.StreetAddress")",
                                width: 100
                                },
                           {
                               field: "PostCode",
                                title: "@T("Admin.Customers.Customers.Fields.ZipPostalCode")",
                                width: 50
                           },
                           {
                               field: "Email",
                               title: "@T("Admin.Customers.Customers.Fields.Email")",
                                width: 100
                    },
                          ]
                        });
                    });
                            </script>

                            <script type="text/javascript">

                    var selectedIds = [];

                    $(document).ready(function () {

                        //search button
                        $('#search-customers').click(function () {
                            var grid = $('#customers-grid').data('kendoGrid');
                            grid.dataSource.page(1); //new search. Set page size to 1
                            //grid.dataSource.read(); we already loaded the grid above using "page" function
                            //clear selected checkboxes
                            $('.checkboxGroups').attr('checked', false).change();
                            selectedIds = [];
                            return false;
                        });


                        @*$("#@Html.FieldIdFor(model => model.SearchCompany)").keydown(function (event) {
                            if (event.keyCode == 13) {
                                $("#search-customers").click();
                                return false;
                            }
                        });*@


                    });





            function additionalData() {



                            @*var data = {
                                SearchCompany: $('#@Html.FieldIdFor(model => model.SearchCompany)').val(),
                                SearchZipPostalCode: $('#@Html.FieldIdFor(model => model.SearchZipPostalCode)').val()
                            };
                            addAntiForgeryToken(data);
                            return data;*@
                        }
                            </script>
                        </td>
                    </tr>
                </table>
            </div>
           
            <div class="col-md-6">

                <div id="googleMap"></div>
            </div>
        </div>
       
        <br />
        <div class="row">
            <div class="col-lg-12" id="partnersLogosWrapper">
                <h2>@T("Uga.Partners.Chains")</h2>
                <div class="partnersLogos">
                    <img src="~/Content/Images/praktiker.jpg" class="img-responsive" />
                    <img src="~/Content/Images/masoutis.jpg" class="img-responsive" />
                    <img src="~/Content/Images/xalkiadakis.jpg" class="img-responsive" />
                    <img src="~/Content/Images/proodos.jpg" class="img-responsive" />
                    <img src="~/Content/Images/ellhnika.jpg" class="img-responsive" />
                </div>
            </div>
        </div>
          
        </div>
</div>

Nop.Plugin.Uga.Partners/Views/Partners/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Partners</title>
    <link href="@Url.Content("~/Plugins/Uga.Partners/Content/styles.css")" type="text/css" rel="stylesheet" />
    <script src="@Url.Content("~/Plugins/Uga.Partners/Scripts/jquery-1.10.2.min.js")"></script>
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
</head>
<body>
    <div class="master-wrapper-page">
        <div class="master-wrapper-main">
            @RenderBody()
        </div>
    </div>
</body>
</html>